# Generated by Django 3.2.8 on 2021-10-21 08:29

from django.db import migrations, models
import plants.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nameComun', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to=plants.models.file_directory_path)),
                ('riego', models.IntegerField(null=True)),
                ('tierra', models.CharField(choices=[('TIE', 'Tierra'), ('ARE', 'Arenosa'), ('ARC', 'Arcillosa'), ('LIM', 'Limosa'), ('TUB', 'Turba'), ('TIZ', 'Tiza')], default='TIE', max_length=3)),
            ],
        ),
    ]
