# Generated by Django 3.2.8 on 2021-10-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='nameComun',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='tierra',
            field=models.CharField(choices=[('TIE', 'Tierra'), ('ARE', 'Arenosa'), ('ARC', 'Arcillosa'), ('LIM', 'Limosa'), ('TUB', 'Turba'), ('TIZ', 'Tiza')], default='TIE', max_length=3),
        ),
    ]
